### ISSUE TITLE
请问怎么在 HandleExample 里面拿到队列名称？

### ISSUE THREAD

**Issue by lyzhang1999** [xiaojiaoyu100/aliyun-mns#3]
aliyun_mns.ReceiveMessage 内看到有所有的阿里云返回的所有字段，但是我现在想在这里拿到队列名，不该写源码的情况下能实现吗？

**Comment by zenghur** [comment]
> aliyun_mns.ReceiveMessage 内看到有所有的阿里云返回的所有字段，但是我现在想在这里拿到队列名，不该写源码的情况下能实现吗？

一个handle对应一个队列名字的

**Comment by lyzhang1999** [comment]
好的，谢谢
